# Generated by Django 5.1.1 on 2024-09-23 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions1', to='Activity.activity')),
                ('second_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions2', to='Activity.activity')),
            ],
        ),
    ]
